theme: minima
title: Techie Learning is an always!!
author: anp-c
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Lets just say that this journey started as soon as I checkin into life and will end when I checkout...

# social links
twitter_username: dont care
github_username:  my business is your business not

show_excerpts: true # set to false to remove excerpts on the homepage
